### ISSUE TITLE
The rtmp_stat does not work with hls

### ISSUE THREAD

**Issue by pointergr** [deluxor/nodejs-nginx-rtmp-balancer#2]
The rtmp_stat does not count hls viewers.

**Comment by deluxor** [comment]
Yep sadly, it does not. Simply because the HLS serving system is based on normal HTTP requests, therefore you cannot count an opening / closing connection, because after the playlist is served the chunks are requested like if they were common files on the webserver, you are basically downloading a file from the server, while on the RTMP you maintain the socket open, and you can actually count it.

There is another solution, use HttpStubStatusModule for nginx:
[https://www.cyberciti.biz/faq/nginx-enable-and-see-current-status-page/](https://www.cyberciti.biz/faq/nginx-enable-and-see-current-status-page/)
That way you can see an overall counting on all requests from your server, but they are not really related to the HLS itself...
